title: "Documentation and Tutorials" 
description: Documentation, tutorials and workflows for the B-Cubed toolbox.
theme: just-the-docs
extra_css:
  - /style.css

search_enabled: true
description: B-Cubed Documentation and Tutorials
color_scheme: 
logo: "images/B3_logo.png"
url: https://lauraAbr.github.io/B-Cubed.Documentation

aux_links:
  Template Repository: https://github.com/LauraAbr/B-Cubed.Documentation
plugins:
  - jekyll-default-layout
