# SITE SETTINGS
title: BioMath, Stellenbosch B-Cubed deliverables
description: Documentation, tutorials and workflows for the BioMath, Stellenbosch B-Cubed toolbox deliverables.
url: https://biomath-lab.github.io/b-cubed
baseurl: ""

# Set a path/url to a logo that will be displayed instead of the title
# logo: assets/sun.png
logo: assets/images/su-logo-crop.png
# Set a path/url to a favicon that will be displayed by the browser
favicon: favicon.ico
# favicon_ico: /assets/images/favicon.ico
# favicon: /assets/favicon.ico

# THEME SETTINGS
theme: just-the-docs

# Just the docs settings
# logo: assets/images/b3-logo.png
# logo: assets/images/sun-logo.png
# logo: assets/sun.png
search_enabled: true
aux_links:
  GitHub: https://github.com/biomath-lab/b-cubed

# Just the docs footer (TODO: currently missing)
last_edit_timestamp: true
gh_edit_link: true
gh_edit_repository: https://github.com/biomath-lab/b-cubed

# Just the docs colours
callouts:
  important:
    color: blue
  note:
    color: yellow

# Just the docs style
# color_scheme: B-Cubedtheme
color_scheme: light.scss
extra_css:
  - assets/css/style.css # TODO: does this work?
sass:
  style: compressed
  sass_dir: _sass

# BUILD SETTINGS
markdown: kramdown
plugins:
  - jekyll-default-layout  
  - jekyll-sass-converter
exclude:
  - README.md

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      path: "dev-guide" # TODO: should be possible to remove this, but breaks styling
      type: "pages"
    values:
      permalink: "/:path/:basename/"
