title: "Documentation and Tutorials" 
description: Documentation, tutorials and workflows for the B-Cubed toolbox.
theme: just-the-docs
# extra_css:
  # - style.css

# search_enabled: true
description: B-Cubed Documentation and Tutorials
# sass:
  # style: compressed
  # sass_dir: _sass
  plugings:
    - jekyll-sass-converter
# color_scheme: B-Cubedtheme
logo: "../images/Blogo.png"
url: https://b-cubed-eu.github.io/documentation/

aux_links:
  Template Repository: https://github.com/b-cubed-eu/documentation
plugins:
  - jekyll-default-layout
