title: "B-Cubed: Documentation and Tutorials" 
description: Documentation, tutorials and workflows for the B-Cubed toolbox.
theme: just-the-docs
search_enabled: true
url: https://LauraAbr.github.io/B-Cubed.Documentation

aux_links:
  Template Repository: https://github.com/LauraAbr/B-Cubed.Documentation
