title: "Documentation and Tutorials" 
description: Documentation, tutorials and workflows for the B-Cubed toolbox.
theme: just-the-docs
search_enabled: true
url: https://B-Cubed.Documentation.github.io/

aux_links:
  Template Repository: https://github.com/LauraAbr/B-Cubed.Documentation
